from pathlib import Path
import re
p=Path('index.html'); s=p.read_text(encoding='utf-8')
for ident in ['anomaly-rankings-v519-css','anomaly-rankings-v519-js']:
    s=re.sub(r'\n?<(script|style) id="'+re.escape(ident)+r'">.*?</\1>\n?','\n',s,flags=re.S)
style=r'''<style id="anomaly-rankings-v519-css">
#anomaly .anomaly-v58{display:none!important}#anomaly .anomaly-rank-v519{display:grid;gap:14px}.ar519-head,.ar519-panel{background:#fff;border:1px solid var(--line);border-radius:20px;padding:16px;box-shadow:var(--shadow)}.ar519-head{background:linear-gradient(145deg,#0b1425,#17345d);color:#fff}.ar519-head h2{margin:5px 0;font-size:22px}.ar519-head p{margin:0;color:#bfd0e5;font-size:10px}.ar519-chips{display:flex;gap:7px;flex-wrap:wrap;margin-top:12px}.ar519-chip{padding:7px 9px;border-radius:999px;background:rgba(255,255,255,.09);border:1px solid rgba(255,255,255,.13);font-size:9px;font-weight:850}.ar519-counts{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:12px}.ar519-count{padding:11px;border-radius:13px;background:rgba(255,255,255,.08);border:1px solid rgba(255,255,255,.1)}.ar519-count span{display:block;color:#b8c9dd;font-size:8px}.ar519-count b{display:block;margin-top:4px;font-size:19px}.ar519-title{display:flex;justify-content:space-between;gap:10px;align-items:flex-end;margin-bottom:10px}.ar519-title h3{margin:0;font-size:16px}.ar519-title small{color:var(--muted);font-size:8px}.ar519-list{display:grid;gap:8px}.ar519-row{display:grid;grid-template-columns:32px minmax(0,1fr) auto;gap:10px;align-items:center;padding:11px;border:1px solid var(--line);border-radius:14px;background:#fff}.ar519-no{width:32px;height:32px;border-radius:10px;background:#eef2f7;display:grid;place-items:center;font-size:9px;font-weight:950}.ar519-name b{display:block;font-size:11px}.ar519-meta{display:flex;gap:8px;flex-wrap:wrap;margin-top:4px;color:var(--muted);font-size:8px}.ar519-tags{display:flex;gap:5px;flex-wrap:wrap;margin-top:5px}.ar519-tag{padding:3px 6px;border-radius:999px;background:#fff3d9;color:#8a5500;font-size:7px;font-weight:900}.ar519-value{text-align:right}.ar519-value b{display:block;font-size:13px}.ar519-value small{display:block;margin-top:3px;color:var(--muted);font-size:7px}.ar519-empty{padding:18px;text-align:center;border:1px dashed #d8dee8;border-radius:14px;color:var(--muted);font-size:9px;background:#fafbfc}.ar519-priority .ar519-row{border-left:4px solid #d94848}.ar519-priority .ar519-no{background:#fff0f0;color:#c83434}@media(max-width:620px){.ar519-row{grid-template-columns:30px minmax(0,1fr)}.ar519-value{grid-column:2;text-align:left}}
</style>'''
js=r'''<script id="anomaly-rankings-v519-js">
(function(){
 const KEY='opsAnomalyThresholdsV58',$=q=>document.querySelector(q),n=v=>Number.isFinite(Number(v))?Number(v):0;
 const esc=v=>String(v??'—').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 const money=v=>new Intl.NumberFormat('zh-TW',{style:'currency',currency:'TWD',maximumFractionDigits:0}).format(n(v)),pct=v=>(n(v)*100).toFixed(2)+'%';
 function thresholds(){try{const t=JSON.parse(localStorage.getItem(KEY)||'null');return t&&Number.isFinite(t.clearance)&&Number.isFinite(t.waste)?t:null}catch{return null}}
 function items(){const m=new Map();(window.rows||[]).forEach(r=>{const k=String(r.item||r.sku||'').trim();if(!k)return;if(!m.has(k))m.set(k,{name:r.item||r.sku,sales:0,clearance:0,waste:0});const x=m.get(k);x.sales+=n(r.sales);x.clearance+=n(r.clearance);x.waste+=n(r.waste)});return [...m.values()].map(x=>{x.cr=x.sales>0?x.clearance/x.sales:0;x.wr=x.sales>0?x.waste/x.sales:0;x.loss=x.clearance+x.waste;x.lr=x.sales>0?x.loss/x.sales:0;return x})}
 function tags(x,t){const a=[];if(x.cr>t.clearance)a.push('出清超標');if(x.wr>t.waste)a.push('報廢超標');if(x.lr>t.clearance+t.waste)a.push('損耗超標');return a}
 function priority(arr,t){const abnormal=arr.filter(x=>tags(x,t).length),totalLoss=arr.reduce((s,x)=>s+x.loss,0),lt=t.clearance+t.waste;abnormal.forEach(x=>{x.lossShare=totalLoss>0?x.loss/totalLoss:0;const ratios=[];if(x.cr>t.clearance)ratios.push(t.clearance?x.cr/t.clearance:0);if(x.wr>t.waste)ratios.push(t.waste?x.wr/t.waste:0);if(x.lr>lt)ratios.push(lt?x.lr/lt:0);x.overRatio=Math.max(1,...ratios);x.dual=x.cr>t.clearance&&x.wr>t.waste;});const maxShare=Math.max(...abnormal.map(x=>x.lossShare),.000001),maxOver=Math.max(...abnormal.map(x=>Math.max(0,x.overRatio-1)),.000001);abnormal.forEach(x=>{const amountNorm=x.lossShare/maxShare,overNorm=Math.max(0,x.overRatio-1)/maxOver;x.priorityScore=amountNorm*.60+overNorm*.30+(x.dual?.10:0)});return abnormal.sort((a,b)=>b.priorityScore-a.priorityScore||b.loss-a.loss).slice(0,5)}
 function row(x,i,kind,t,priorityMode=false){let rate,limit,label;if(kind==='c'){rate=x.cr;limit=t.clearance;label='出清'}else if(kind==='w'){rate=x.wr;limit=t.waste;label='報廢'}else{rate=x.lr;limit=t.clearance+t.waste;label='損耗'}const tg=tags(x,t),extra=priorityMode?`<span>全店損耗占比 ${pct(x.lossShare)}</span><span>超標倍數 ${x.overRatio.toFixed(2)}×</span>`:'';return `<div class="ar519-row"><div class="ar519-no">${i+1}</div><div class="ar519-name"><b>${esc(x.name)}</b><div class="ar519-meta"><span>營業額 ${money(x.sales)}</span><span>出清 ${money(x.clearance)}</span><span>報廢 ${money(x.waste)}</span><span>損耗 ${money(x.loss)}</span>${extra}</div><div class="ar519-tags">${tg.filter(z=>priorityMode||z!==label+'超標').map(z=>`<span class="ar519-tag">${z}</span>`).join('')}</div></div><div class="ar519-value"><b>${pct(rate)}</b><small>${priorityMode?`損耗率｜警戒 ${pct(limit)}`:`警戒 ${pct(limit)}｜超標 +${((rate-limit)*100).toFixed(2)}pp`}</small></div></div>`}
 function rank(arr,kind,t){let limit=kind==='c'?t.clearance:kind==='w'?t.waste:t.clearance+t.waste,key=kind==='c'?'cr':kind==='w'?'wr':'lr';return arr.filter(x=>x[key]>limit).sort((a,b)=>(b[key]-limit)/(limit||.000001)-(a[key]-limit)/(limit||.000001)||b.loss-a.loss).slice(0,20)}
 function period(){const rs=window.rows||[],v=[];rs.forEach(r=>{for(const k of ['periodStart','periodEnd','date'])if(r[k])v.push(String(r[k]).slice(0,10))});v.sort();return v.length?`${v[0]} ～ ${v[v.length-1]}`:'—'}
 function render(){const page=$('#anomaly');if(!page)return;let root=page.querySelector('.anomaly-rank-v519');if(!root){root=document.createElement('div');root.className='anomaly-rank-v519';const old=page.querySelector('.anomaly-v58,.anomaly-center-panel,.event-panel');old?old.before(root):page.appendChild(root)}const t=thresholds();if(!t){root.innerHTML='<section class="ar519-head"><h2>異常排名</h2><p>尚未設定判定基準。請重新匯入資料並在最後一步設定警戒值。</p></section>';return}const a=items(),c=rank(a,'c',t),w=rank(a,'w',t),l=rank(a,'l',t),pri=priority(a,t);function panel(title,sub,arr,kind,cls='',pm=false){return `<section class="ar519-panel ${cls}"><div class="ar519-title"><div><h3>${title}</h3><small>${sub}</small></div></div><div class="ar519-list">${arr.length?arr.map((x,i)=>row(x,i,kind,t,pm)).join(''):'<div class="ar519-empty">目前沒有商品超過這項警戒值。</div>'}</div></section>`}root.innerHTML=`<section class="ar519-head"><div style="font-size:8px;font-weight:900;letter-spacing:.15em;color:#9db8e8">ANOMALY CENTER</div><h2>異常排名</h2><p>資料期間 ${period()}｜異常榜找異常；改善優先榜找最值得處理的異常。</p><div class="ar519-chips"><span class="ar519-chip">出清率警戒 ${pct(t.clearance)}</span><span class="ar519-chip">報廢率警戒 ${pct(t.waste)}</span><span class="ar519-chip">損耗率警戒 ${pct(t.clearance+t.waste)}</span></div><div class="ar519-counts"><div class="ar519-count"><span>出清超標</span><b>${a.filter(x=>x.cr>t.clearance).length}</b></div><div class="ar519-count"><span>報廢超標</span><b>${a.filter(x=>x.wr>t.waste).length}</b></div><div class="ar519-count"><span>損耗超標</span><b>${a.filter(x=>x.lr>t.clearance+t.waste).length}</b></div></div></section>${panel('改善優先商品 Top 5','金額影響 60%＋超標程度 30%＋出清/報廢雙重異常 10%。不顯示評分。',pri,'l','ar519-priority',true)}${panel('出清率超標 Top 20','只列超過出清率警戒值的商品。',c,'c')}${panel('報廢率超標 Top 20','只列超過報廢率警戒值的商品。',w,'w')}${panel('損耗率超標 Top 20','損耗率＝（出清＋報廢）÷營業額。',l,'l')}`}
 const old=window.renderAll;if(typeof old==='function')window.renderAll=function(){const r=old.apply(this,arguments);setTimeout(render,0);return r};document.addEventListener('DOMContentLoaded',render);setTimeout(render,0);window.renderAnomalyRankingsV519=render;
})();
</script>'''
s=s.replace('</head>',style+'</head>');s=s.replace('</body>',js+'</body>');p.write_text(s,encoding='utf-8');print('anomaly rankings v5.19.1 weighted priority injected')