from pathlib import Path
import re
p=Path('index.html'); s=p.read_text(encoding='utf-8')
for ident in ['anomaly-center-v58-css','anomaly-center-v58-js']:
    s=re.sub(r'\n?<(script|style) id="'+re.escape(ident)+r'">.*?</\1>\n?','\n',s,flags=re.S)
style=r'''<style id="anomaly-center-v58-css">
#anomaly .anomaly-center-panel{display:none!important}
#anomaly .anomaly-v58{display:grid;gap:14px;margin-bottom:14px}
#anomaly .av58-hero{padding:18px;border-radius:22px;background:linear-gradient(145deg,#0b1425,#17345d);color:#fff;box-shadow:0 16px 38px rgba(13,31,58,.18)}
#anomaly .av58-top{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.av58-kicker{font-size:9px;font-weight:900;letter-spacing:.16em;color:#9db8e8}.av58-hero h2{margin:6px 0 5px;font-size:22px}.av58-hero p{margin:0;color:#bfd0e5;font-size:11px;line-height:1.55}.av58-settings{border:1px solid rgba(255,255,255,.18);background:rgba(255,255,255,.09);color:#fff;border-radius:12px;padding:9px 11px;font-size:10px;font-weight:900;white-space:nowrap}
#anomaly .av58-baseline{margin-top:14px;display:flex;gap:8px;flex-wrap:wrap}.av58-chip{padding:7px 9px;border-radius:999px;background:rgba(255,255,255,.09);border:1px solid rgba(255,255,255,.12);font-size:10px;font-weight:800;color:#dbe7f5}
#anomaly .av58-gate{padding:22px;border:1px solid #dbe3ee;border-radius:20px;background:#fff;text-align:center;box-shadow:var(--shadow)}.av58-gate-icon{width:48px;height:48px;border-radius:15px;background:#eef3ff;color:#2c64f1;display:grid;place-items:center;margin:0 auto 12px;font-size:20px}.av58-gate h3{margin:0;font-size:18px}.av58-gate p{margin:7px auto 16px;max-width:520px;color:var(--muted);font-size:11px;line-height:1.6}.av58-start{border:0;border-radius:12px;background:#2c64f1;color:#fff;padding:11px 15px;font-size:11px;font-weight:900}
#anomaly .av58-summary{display:grid;grid-template-columns:repeat(3,1fr);gap:9px}.av58-stat{padding:13px;border:1px solid var(--line);border-radius:15px;background:#fff}.av58-stat span{display:block;color:var(--muted);font-size:9px;font-weight:800}.av58-stat strong{display:block;margin-top:5px;font-size:22px}.av58-stat.high strong{color:#c83d3d}.av58-stat.watch strong{color:#a96a10}
#anomaly .av58-list{display:grid;gap:10px}.av58-card{padding:14px;border:1px solid var(--line);border-radius:17px;background:#fff;box-shadow:0 7px 20px rgba(23,43,77,.05)}.av58-card.high{border-left:4px solid #d94848}.av58-card.watch{border-left:4px solid #e19a2b}.av58-card-head{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}.av58-card h4{margin:0;font-size:14px}.av58-badge{padding:5px 8px;border-radius:999px;font-size:9px;font-weight:900}.av58-card.high .av58-badge{background:#feecec;color:#c83434}.av58-card.watch .av58-badge{background:#fff3d9;color:#9a5a00}.av58-metrics{display:flex;gap:12px;flex-wrap:wrap;margin-top:9px}.av58-metrics span{font-size:10px;color:var(--muted)}.av58-metrics b{color:var(--ink);margin-left:3px}.av58-why{margin-top:10px;padding-top:10px;border-top:1px dashed #dfe5ec;font-size:10px;line-height:1.55;color:#59677a}.av58-action{margin-top:7px;font-size:10px;line-height:1.55;color:#26374d}.av58-action b{color:#0b63ce}.av58-empty{padding:18px;text-align:center;border:1px dashed #d8dee8;border-radius:14px;color:var(--muted);font-size:10px;background:#fafbfc}
.av58-modal{position:fixed;inset:0;z-index:100;background:rgba(6,14,28,.48);display:none;align-items:flex-end;justify-content:center;padding:16px}.av58-modal.open{display:flex}.av58-sheet{width:min(560px,100%);background:#fff;border-radius:22px;padding:18px;box-shadow:0 24px 70px rgba(0,0,0,.25)}.av58-sheet h3{margin:0;font-size:18px}.av58-sheet p{margin:5px 0 14px;color:var(--muted);font-size:10px;line-height:1.5}.av58-fields{display:grid;grid-template-columns:1fr 1fr;gap:10px}.av58-field label{display:block;margin-bottom:6px;font-size:10px;font-weight:850;color:#475467}.av58-input{display:flex;align-items:center;border:1px solid var(--line);border-radius:12px;padding:0 10px;background:#fff}.av58-input input{width:100%;border:0;outline:0;padding:11px 2px;font-size:16px;font-weight:850}.av58-input span{font-size:11px;color:var(--muted)}.av58-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:16px}.av58-cancel,.av58-save{border:0;border-radius:11px;padding:10px 13px;font-size:10px;font-weight:900}.av58-cancel{background:#eef1f5;color:#475467}.av58-save{background:#2c64f1;color:#fff}
@media(max-width:620px){#anomaly .av58-summary{grid-template-columns:1fr 1fr 1fr}.av58-stat{padding:10px}.av58-stat strong{font-size:19px}.av58-fields{grid-template-columns:1fr}.av58-top{align-items:center}.av58-hero h2{font-size:20px}}
</style>'''
js=r'''<script id="anomaly-center-v58-js">
(function(){
 const KEY='opsAnomalyThresholdsV58';
 const $=s=>document.querySelector(s), esc2=v=>String(v??'—').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 const pct2=v=>v==null||!Number.isFinite(Number(v))?'—':(Number(v)*100).toFixed(2)+'%';
 const money2=v=>v==null||!Number.isFinite(Number(v))?'—':new Intl.NumberFormat('zh-TW',{style:'currency',currency:'TWD',maximumFractionDigits:0}).format(Number(v));
 function getT(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');return x&&Number.isFinite(x.clearance)&&Number.isFinite(x.waste)?x:null}catch{return null}}
 function setT(x){localStorage.setItem(KEY,JSON.stringify(x))}
 function ensure(){const page=$('#anomaly');if(!page)return null;let root=page.querySelector('.anomaly-v58');if(root)return root;root=document.createElement('div');root.className='anomaly-v58';const old=page.querySelector('.anomaly-center-panel');old?old.before(root):page.querySelector('.event-panel')?.before(root);document.body.insertAdjacentHTML('beforeend',`<div class="av58-modal" id="av58Modal"><div class="av58-sheet"><h3>異常判定基準</h3><p>設定門市可接受的出清率與報廢率。未設定前，OpsPilot 不會產生出清／報廢異常建議。</p><div class="av58-fields"><div class="av58-field"><label>出清率警戒值</label><div class="av58-input"><input id="av58Clearance" type="number" min="0" max="100" step="0.1" inputmode="decimal" placeholder="例如 8"><span>%</span></div></div><div class="av58-field"><label>報廢率警戒值</label><div class="av58-input"><input id="av58Waste" type="number" min="0" max="100" step="0.1" inputmode="decimal" placeholder="例如 5"><span>%</span></div></div></div><div class="av58-actions"><button class="av58-cancel" type="button">取消</button><button class="av58-save" type="button">儲存並開始分析</button></div></div></div>`);return root}
 function aggregateItems(){const m=new Map();(window.rows||[]).forEach(r=>{const k=String(r.item||r.sku||'').trim();if(!k)return;if(!m.has(k))m.set(k,{name:r.item||r.sku,sales:null,clearance:null,waste:null});const x=m.get(k);for(const f of ['sales','clearance','waste'])if(r[f]!=null&&Number.isFinite(Number(r[f])))x[f]=(x[f]??0)+Number(r[f])});return [...m.values()].map(x=>({...x,clearanceRate:x.sales>0&&x.clearance!=null?x.clearance/x.sales:null,wasteRate:x.sales>0&&x.waste!=null?x.waste/x.sales:null}))}
 function open(){const t=getT();$('#av58Clearance').value=t?(t.clearance*100).toFixed(2).replace(/\.00$/,''):'';$('#av58Waste').value=t?(t.waste*100).toFixed(2).replace(/\.00$/,''):'';$('#av58Modal').classList.add('open')}
 function close(){$('#av58Modal')?.classList.remove('open')}
 function render(){const root=ensure();if(!root)return;const t=getT();root.innerHTML=`<section class="av58-hero"><div class="av58-top"><div><div class="av58-kicker">ANOMALY CENTER</div><h2>需要介入的異常</h2><p>${t?'依你設定的門市標準判斷，不把系統猜測當成異常。':'先設定門市標準，OpsPilot 才開始產生出清與報廢建議。'}</p></div><button type="button" class="av58-settings">⚙︎ 判定設定</button></div>${t?`<div class="av58-baseline"><span class="av58-chip">出清率 &gt; ${pct2(t.clearance)}</span><span class="av58-chip">報廢率 &gt; ${pct2(t.waste)}</span></div>`:''}</section><div class="av58-results"></div>`;const box=root.querySelector('.av58-results');if(!t){box.innerHTML=`<section class="av58-gate"><div class="av58-gate-icon">◎</div><h3>請先設定異常判定基準</h3><p>輸入門市可接受的出清率與報廢率後，才會開始判斷商品是否超標並產生處理建議。</p><button class="av58-start" type="button">設定並開始分析</button></section>`;return}if(!window.confirmed||!(window.rows||[]).length){box.innerHTML='<div class="av58-empty">基準已設定。匯入資料後開始判斷異常。</div>';return}const items=aggregateItems(), arr=[];items.forEach(x=>{if(x.clearanceRate!=null&&x.clearanceRate>t.clearance)arr.push({...x,kind:'出清',rate:x.clearanceRate,limit:t.clearance,amount:x.clearance,over:x.clearanceRate-t.clearance});if(x.wasteRate!=null&&x.wasteRate>t.waste)arr.push({...x,kind:'報廢',rate:x.wasteRate,limit:t.waste,amount:x.waste,over:x.wasteRate-t.waste})});arr.sort((a,b)=>b.over-a.over||Number(b.amount||0)-Number(a.amount||0));const high=arr.filter(x=>x.rate>=x.limit*1.5).length,watch=arr.length-high;box.innerHTML=`<div class="av58-summary"><div class="av58-stat"><span>超標項目</span><strong>${arr.length}</strong></div><div class="av58-stat high"><span>明顯超標</span><strong>${high}</strong></div><div class="av58-stat watch"><span>需關注</span><strong>${watch}</strong></div></div><div class="av58-list" style="margin-top:10px">${arr.length?arr.slice(0,10).map(x=>{const level=x.rate>=x.limit*1.5?'high':'watch',over=(x.over*100).toFixed(2);return `<article class="av58-card ${level}"><div class="av58-card-head"><div><h4>${esc2(x.name)}</h4><div class="av58-metrics"><span>${x.kind}率 <b>${pct2(x.rate)}</b></span><span>警戒值 <b>${pct2(x.limit)}</b></span><span>超標 <b>+${over}pp</b></span></div></div><span class="av58-badge">${level==='high'?'明顯超標':'需關注'}</span></div><div class="av58-why">資料判讀：${x.kind}率已超過你設定的門市警戒值；${x.kind}金額 ${money2(x.amount)}。</div><div class="av58-action"><b>建議動作：</b>${x.kind==='出清'?'檢查生產量、最後生產時段與折價節奏，再決定是否小幅調整。':'檢查備貨量、保存期限與時段性剩量，再決定是否調整。'}</div></article>`}).join(''):'<div class="av58-empty">目前沒有商品超過你設定的出清率／報廢率警戒值。</div>'}</div>`}
 document.addEventListener('click',e=>{if(e.target.closest('.av58-settings,.av58-start'))open();if(e.target.closest('.av58-cancel')||e.target.id==='av58Modal')close();if(e.target.closest('.av58-save')){const c=Number($('#av58Clearance').value),w=Number($('#av58Waste').value);if(!Number.isFinite(c)||!Number.isFinite(w)||c<0||w<0||c>100||w>100){if(typeof toast==='function')toast('請輸入 0～100 的出清率與報廢率');return}setT({clearance:c/100,waste:w/100});close();render();if(typeof toast==='function')toast('已儲存判定基準，開始分析')}});
 const old=window.renderAll;if(typeof old==='function')window.renderAll=function(){const r=old.apply(this,arguments);setTimeout(render,0);return r};
 document.addEventListener('DOMContentLoaded',render);setTimeout(render,0);window.renderAnomalyCenterV58=render;
})();
</script>'''
s=s.replace('</head>',style+'</head>')
s=s.replace('</body>',js+'</body>')
p.write_text(s,encoding='utf-8')
print('anomaly center v5.8 safe layer injected')
