from pathlib import Path
import re
p=Path('index.html'); s=p.read_text(encoding='utf-8')
for ident in ['analysis-layout-v55-css','analysis-layout-v55-js','analysis-layout-v56-css','analysis-layout-v56-js']:
 s=re.sub(r'\n?<(script|style) id="'+re.escape(ident)+r'">.*?</\1>\n?','\n',s,flags=re.S)
style=r'''<style id="analysis-layout-v56-css">
#analysis .analysis-flow-v56{display:grid;gap:14px;margin-top:12px}.analysis-block-v56{border:1px solid var(--line);border-radius:20px;background:#fff;box-shadow:var(--shadow);overflow:hidden}.analysis-block-v56 .head-v56{display:flex;align-items:center;gap:10px;padding:14px 16px;font-weight:950}.analysis-block-v56 .num-v56{width:30px;height:30px;border-radius:50%;display:grid;place-items:center;color:#fff}.sales-v56{border-color:#cfe0ff}.sales-v56 .head-v56{color:#2156b7}.sales-v56 .num-v56{background:#2C64F1}.clearance-v56{border-color:#cfe9dd}.clearance-v56 .head-v56{color:#16805B}.clearance-v56 .num-v56{background:#16805B}.waste-v56{border-color:#ffd9cf}.waste-v56 .head-v56{color:#c64f31}.waste-v56 .num-v56{background:#e85d3d}.loss-v56{border-color:#d9e0ea}.loss-v56 .head-v56{color:#475467}.loss-v56 .num-v56{background:#52637a}.analysis-block-v56>.panel{border:0;box-shadow:none;margin:0;border-radius:0}.interval-v56{border-color:#cfe0ff}.interval-v56>.loss-top10-v49{display:block!important;margin:0!important;padding:14px!important}.metric-v56{margin:0 14px 12px;padding:14px;border:1px solid var(--line);border-radius:15px}.metric-v56 strong{display:block;font-size:26px;margin-top:5px}.sub-v56{padding:8px 14px 14px}.sub-v56 h4{margin:5px 0 10px}.rank-v56{display:grid;gap:8px}.rankrow-v56{display:grid;grid-template-columns:28px minmax(0,1fr) auto;gap:9px;align-items:center;padding:10px;border:1px solid var(--line);border-radius:13px}.rankrow-v56 .r{font-weight:950}.rankrow-v56 small{display:block;color:var(--muted);margin-top:3px}.detail-v56{margin:0 14px 14px;border:1px solid var(--line);border-radius:14px;overflow:hidden}.detail-v56 button{width:100%;border:0;background:#fff;padding:12px 14px;display:flex;justify-content:space-between;font-weight:900}.detail-v56 .body{display:none;padding:0 10px 10px}.detail-v56.open .body{display:block}.detail-v56 .table-wrap{max-height:420px}.legacy-analysis-detail-v56{display:none!important}.waste-v56 #lossSplitPanel>.table-wrap,.waste-v56 #lossSplitPanel>.loss-top10-v49{display:none!important}@media(max-width:760px){.analysis-block-v56 .head-v56{padding:12px}.sub-v56{padding:7px 10px 11px}.metric-v56,.detail-v56{margin-left:10px;margin-right:10px}}
</style>'''
js=r'''<script id="analysis-layout-v56-js">(function(){
const money=v=>v==null||isNaN(Number(v))?'—':new Intl.NumberFormat('zh-TW',{style:'currency',currency:'TWD',maximumFractionDigits:0}).format(Number(v)), pct=v=>v==null?'—':(Number(v)*100).toFixed(1)+'%', esc=v=>String(v??'—').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])), rows=()=>Array.isArray(window.rows)?window.rows:[];
function panel(el){return el?(el.classList?.contains('panel')?el:el.closest('.panel')):null} function find(page,re){return [...page.querySelectorAll('.panel')].find(x=>re.test((x.textContent||'').replace(/\s+/g,' ')))}
function agg(){const m=new Map();rows().forEach(r=>{let k=String(r.sku||r.item||'').trim();if(!k)return;let x=m.get(k)||{name:r.item||r.sku,sales:null,clearance:null,waste:null};['sales','clearance','waste'].forEach(f=>{if(r[f]!=null)x[f]=(x[f]??0)+Number(r[f])});m.set(k,x)});return [...m.values()].map(x=>({...x,loss:x.clearance==null&&x.waste==null?null:(x.clearance||0)+(x.waste||0),clearanceRate:x.sales>0&&x.clearance!=null?x.clearance/x.sales:null,wasteRate:x.sales>0&&x.waste!=null?x.waste/x.sales:null,lossRate:x.sales>0&&(x.clearance!=null||x.waste!=null)?((x.clearance||0)+(x.waste||0))/x.sales:null}))}
function block(kind,no,title){let x=document.createElement('section');x.className=`analysis-block-v56 ${kind}-v56`;x.innerHTML=`<div class="head-v56"><span class="num-v56">${no}</span><b>${title}</b></div>`;return x}
function rank(sec,title,key,isRate=false){let a=agg().filter(x=>x[key]!=null).sort((a,b)=>b[key]-a[key]).slice(0,10),d=document.createElement('div');d.className='sub-v56';d.innerHTML=`<h4>${title}</h4><div class="rank-v56">${a.map((x,i)=>`<div class="rankrow-v56"><b>${i+1}</b><div class="r">${esc(x.name)}<small>營業額 ${money(x.sales)}</small></div><b>${isRate?pct(x[key]):money(x[key])}</b></div>`).join('')||'<div class="empty">無資料</div>'}</div>`;sec.appendChild(d)}
function priority(sec,kind){let amount=kind==='clearance'?'clearance':kind==='waste'?'waste':'loss',rate=kind+'Rate',a=agg().filter(x=>x[amount]!=null&&x[rate]!=null);let maxA=Math.max(1,...a.map(x=>x[amount]||0)),maxR=Math.max(.000001,...a.map(x=>x[rate]||0));a.forEach(x=>x.score=.6*(x[amount]/maxA)+.4*(x[rate]/maxR));a.sort((a,b)=>b.score-a.score);let d=document.createElement('div');d.className='sub-v56';d.innerHTML=`<h4>改善優先度</h4><div class="rank-v56">${a.slice(0,10).map((x,i)=>`<div class="rankrow-v56"><b>${i+1}</b><div class="r">${esc(x.name)}<small>${money(x[amount])} · ${pct(x[rate])}</small></div><b>${Math.round(x.score*100)}</b></div>`).join('')||'<div class="empty">無資料</div>'}</div>`;sec.appendChild(d)}
function detail(sec,kind){let d=document.createElement('div');d.className='detail-v56';d.innerHTML=`<button><span>${kind==='clearance'?'出清':kind==='waste'?'報廢':kind==='loss'?'損耗':'銷售'}資料明細</span><span>查看明細 ⌄</span></button><div class="body"></div>`;d.querySelector('button').onclick=()=>{d.classList.toggle('open');if(!d.classList.contains('open'))return;let a=rows().filter(r=>kind==='sales'?r.sales!=null:kind==='clearance'?r.clearance!=null:kind==='waste'?r.waste!=null:r.clearance!=null||r.waste!=null);d.querySelector('.body').innerHTML=`<div class="table-wrap"><table><thead><tr><th>商品</th><th>營業額</th><th>出清</th><th>報廢</th></tr></thead><tbody>${a.map(r=>`<tr><td>${esc(r.item||r.sku)}</td><td>${money(r.sales)}</td><td>${money(r.clearance)}</td><td>${money(r.waste)}</td></tr>`).join('')}</tbody></table></div>`};sec.appendChild(d)}
function total(sec,kind){let a=rows(),sales=0,n=0,has=false;a.forEach(r=>{if(r.sales!=null)sales+=Number(r.sales);let v=kind==='clearance'?r.clearance:kind==='waste'?r.waste:(r.clearance==null&&r.waste==null?null:Number(r.clearance||0)+Number(r.waste||0));if(v!=null){n+=Number(v);has=true}});let d=document.createElement('div');d.className='metric-v56';d.innerHTML=`<span>總${kind==='clearance'?'出清':kind==='waste'?'報廢':'損耗'}率</span><strong>${has&&sales>0?pct(n/sales):'無資料'}</strong><small>${has?money(n):'無資料'} ÷ ${sales?money(sales):'無資料'}</small>`;sec.appendChild(d)}
function apply(){let page=document.getElementById('analysis');if(!page)return;let old=page.querySelector('.analysis-flow-v56');if(old)old.remove();let flow=document.createElement('div');flow.className='analysis-flow-v56';let tb=page.querySelector('.toolbar');tb?tb.after(flow):page.appendChild(flow);let sales=panel(page.querySelector('.top10-sales-panel'))||panel(page.querySelector('#salesTop10List'))||find(page,/平日\s*\/\s*假日.*Top\s*10/i), clear=panel(page.querySelector('#clearanceRateSummary'))||find(page,/出清率分析/i), waste=document.getElementById('lossSplitPanel'), loss=panel(page.querySelector('#analysisBars'))||find(page,/品項損耗排行|每日損耗趨勢/i);if(!sales)return;
let interval=page.querySelector('.loss-top10-v49');if(interval){let w=document.createElement('section');w.className='analysis-block-v56 interval-v56';w.appendChild(interval);flow.appendChild(w)}
let s=block('sales',1,'營業額分析');s.appendChild(sales);flow.appendChild(s);detail(s,'sales');
let c=block('clearance',2,'出清分析');total(c,'clearance');if(clear)c.appendChild(clear);rank(c,'Top 10 出清金額','clearance');rank(c,'Top 10 出清率','clearanceRate',true);priority(c,'clearance');detail(c,'clearance');flow.appendChild(c);
let w=block('waste',3,'報廢分析');total(w,'waste');if(waste)w.appendChild(waste);rank(w,'Top 10 報廢金額','waste');rank(w,'Top 10 報廢率','wasteRate',true);priority(w,'waste');detail(w,'waste');flow.appendChild(w);
let l=block('loss',4,'損耗總覽');total(l,'loss');if(loss)l.appendChild(loss);rank(l,'Top 10 損耗金額','loss');rank(l,'Top 10 損耗率','lossRate',true);priority(l,'loss');detail(l,'loss');flow.appendChild(l);
[...page.querySelectorAll('.panel')].filter(x=>/資料明細/.test(x.textContent||'')&&!x.closest('.analysis-block-v56')).forEach(x=>x.classList.add('legacy-analysis-detail-v56'))}
document.addEventListener('DOMContentLoaded',()=>setTimeout(apply,0));let old=window.renderAll;window.renderAll=function(){if(typeof old==='function')old.apply(this,arguments);apply()};setTimeout(apply,120)})();</script>'''
s=s.replace('</head>',style+'</head>',1).replace('</body>',js+'</body>',1);p.write_text(s,encoding='utf-8');print('v5.6 structured analysis deployed')
