from pathlib import Path
p=Path('index.html')
s=p.read_text(encoding='utf-8')
if 'opspilot-v6-product-rebuild' in s:
    print('v6 already applied'); raise SystemExit
css=r'''<style id="opspilot-v6-product-rebuild">
:root{--v6-bg:#EEF3F8;--v6-surface:#FFFFFF;--v6-ink:#111827;--v6-text:#334155;--v6-muted:#667085;--v6-line:#DCE4EE;--v6-navy:#111827;--v6-blue:#315FE8;--v6-blue-soft:#EEF3FF;--v6-amber:#A66B17;--v6-amber-soft:#FFF7E8;--v6-red:#C84A46;--v6-red-soft:#FFF1F0;--v6-green:#16805B}
html,body{background:var(--v6-bg)!important;color:var(--v6-ink)!important}.content{max-width:1180px!important;padding:18px!important}.page{padding-bottom:18px}.page-head{margin-bottom:16px!important}.page-head h1{font-size:30px!important;letter-spacing:-.04em!important}.page-head p{font-size:13px!important;color:var(--v6-muted)!important;line-height:1.55!important}
.panel,.exec-v513 .card,.analysis-safe-v57 .as57-card,.ar519-panel{background:var(--v6-surface)!important;border:1px solid var(--v6-line)!important;border-radius:22px!important;box-shadow:0 10px 30px rgba(30,41,59,.06)!important;padding:18px!important}.panel-head h3,.ar519-title h3{font-size:20px!important}.panel-head p,.ar519-title small{font-size:12px!important;line-height:1.5!important;color:var(--v6-muted)!important}
.rank-item,.metric,.mini-card,.ar519-row,.analysis-safe-v57 .as57-item{border:1px solid var(--v6-line)!important;border-radius:16px!important;background:#fff!important}.rank-main b,.ar519-name b{font-size:14px!important}.rank-main small,.ar519-meta,.ar519-value small{font-size:11px!important;line-height:1.45!important;color:var(--v6-muted)!important}.rank-money b,.ar519-value b{font-size:18px!important}
/* header / brand */
.topbar{background:rgba(238,243,248,.92)!important;border-bottom:1px solid #D8E1EC!important}.brand-mark{background:linear-gradient(145deg,#14264A,#315FE8)!important;box-shadow:0 8px 20px rgba(49,95,232,.24)!important}.brand strong{font-size:17px!important}
/* bottom nav: one cohesive product component */
.bottom-nav{background:#111827!important;border:1px solid rgba(255,255,255,.08)!important;box-shadow:0 18px 46px rgba(15,23,42,.28)!important;border-radius:24px!important}.bottom-nav button,.bottom-nav .nav-item{color:#9AA7B8!important}.bottom-nav .active,.bottom-nav button.active{background:#fff!important;color:#111827!important;border-radius:19px!important}.bottom-nav svg{width:25px!important;height:25px!important;stroke-width:1.9!important}.bottom-nav span{font-size:12px!important;font-weight:800!important}
/* executive / overview: reduce blank white feeling with one controlled hero and semantic accents */
#executive .exec-v513 .hero,#executive .hero{background:linear-gradient(135deg,#101828 0%,#172B4D 62%,#315FE8 100%)!important;border-radius:24px!important}.exec-v513 .card h3{font-size:19px!important}.exec-v513 .card small,.exec-v513 .sub{font-size:12px!important;color:var(--v6-muted)!important}
/* insight: result first, then structure; not decorative color blocks */
#overview .v521-insights{display:none!important}#overview .v522-insight-structure{margin-top:14px!important}.v522-structure-head{border:1px solid var(--v6-line)!important;border-radius:22px!important;background:linear-gradient(120deg,#fff,#F6F8FC)!important;box-shadow:0 10px 30px rgba(30,41,59,.05)!important}.v522-structure-head h3{font-size:22px!important}.v522-structure-head p,.v522-card p{font-size:13px!important;color:var(--v6-muted)!important}.v522-card{border:1px solid var(--v6-line)!important;border-radius:18px!important;box-shadow:none!important}.v522-card b{font-size:16px!important}
/* anomaly: priority is a management decision module; the rest are compact detection lists */
#anomaly .ar519-head{background:linear-gradient(135deg,#101828,#1D355A)!important;border-radius:24px!important;padding:20px!important}.ar519-head h2{font-size:26px!important}.ar519-head p{font-size:12px!important;line-height:1.55!important}.ar519-priority{border-top:4px solid var(--v6-red)!important}.ar519-priority .ar519-row{border-left:4px solid var(--v6-red)!important;background:linear-gradient(100deg,#FFF8F7 0%,#fff 36%)!important}.ar519-priority .ar519-value b{font-size:21px!important}.ar519-panel:not(.ar519-priority) .ar519-list{gap:0!important;border:1px solid var(--v6-line);border-radius:16px;overflow:hidden}.ar519-panel:not(.ar519-priority) .ar519-row{border:0!important;border-bottom:1px solid #E8EDF3!important;border-radius:0!important;padding:13px 14px!important}.ar519-panel:not(.ar519-priority) .ar519-row:last-child{border-bottom:0!important}.ar519-tag{font-size:10px!important;padding:4px 7px!important;background:var(--v6-amber-soft)!important;color:#85510C!important}.ar519-no{font-size:12px!important}
/* added clearance amount ranking */
.v6-clearance-amount{border-top:4px solid var(--v6-amber)!important}.v6-clearance-amount .ar519-row{background:linear-gradient(90deg,#FFFDF8,#fff)!important}.v6-clearance-amount .ar519-value b{color:var(--v6-amber)!important}
/* analysis remains functional, visually aligned */
#analysis .analysis-safe-v57 .as57-card{border-top:3px solid #CBD5E1!important}#analysis .analysis-safe-v57 .as57-card:nth-child(1){border-top-color:var(--v6-blue)!important}#analysis .analysis-safe-v57 .as57-card:nth-child(2){border-top-color:var(--v6-amber)!important}#analysis .analysis-safe-v57 .as57-card:nth-child(3){border-top-color:var(--v6-red)!important}
@media(max-width:700px){.content{padding:14px!important}.page-head h1{font-size:27px!important}.panel,.exec-v513 .card,.analysis-safe-v57 .as57-card,.ar519-panel{padding:16px!important;border-radius:20px!important}.ar519-row{grid-template-columns:38px minmax(0,1fr)!important;gap:10px!important}.ar519-value{grid-column:2!important;text-align:left!important}.ar519-name b{font-size:15px!important}.ar519-meta{font-size:12px!important;gap:7px!important}.ar519-value b{font-size:20px!important}.ar519-value small{font-size:12px!important}.v522-grid{grid-template-columns:1fr!important}.v522-card p{font-size:14px!important}.bottom-nav span{font-size:11px!important}}
</style>'''
js=r'''<script id="opspilot-v6-product-rebuild-js">
(()=>{
 const n=v=>Number.isFinite(Number(v))?Number(v):0,esc=v=>String(v??'—').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])),money=v=>new Intl.NumberFormat('zh-TW',{style:'currency',currency:'TWD',maximumFractionDigits:0}).format(n(v));
 function aggregate(){const m=new Map();(window.rows||[]).forEach(r=>{const k=String(r.item||r.sku||'').trim();if(!k)return;if(!m.has(k))m.set(k,{name:r.item||r.sku,sales:0,clearance:0,waste:0});const x=m.get(k);x.sales+=n(r.sales);x.clearance+=n(r.clearance);x.waste+=n(r.waste)});return [...m.values()]}
 function row(x,i){return `<div class="ar519-row"><div class="ar519-no">${i+1}</div><div class="ar519-name"><b>${esc(x.name)}</b><div class="ar519-meta"><span>營業額 ${money(x.sales)}</span><span>出清 ${money(x.clearance)}</span><span>報廢 ${money(x.waste)}</span></div></div><div class="ar519-value"><b>${money(x.clearance)}</b><small>出清金額</small></div></div>`}
 function clearanceTop10(){const root=document.querySelector('#anomaly .anomaly-rank-v519');if(!root)return;let sec=root.querySelector('.v6-clearance-amount');const pri=root.querySelector('.ar519-priority');if(!sec){sec=document.createElement('section');sec.className='ar519-panel v6-clearance-amount';if(pri)pri.after(sec);else root.append(sec)}const a=aggregate().filter(x=>x.clearance>0).sort((a,b)=>b.clearance-a.clearance).slice(0,10);sec.innerHTML=`<div class="ar519-title"><div><h3>出清金額 Top 10</h3><small>依出清金額由高到低排序，這是金額排行，不代表異常程度。</small></div></div><div class="ar519-list">${a.length?a.map(row).join(''):'<div class="ar519-empty">目前沒有出清資料。</div>'}</div>`}
 function anomalyLabels(){const root=document.querySelector('#anomaly .anomaly-rank-v519');if(!root)return;root.querySelectorAll('.ar519-panel').forEach(sec=>{const h=sec.querySelector('h3'),sub=sec.querySelector('.ar519-title small');if(!h||!sub)return;if(/改善優先/.test(h.textContent))sub.textContent='管理決策｜先找異常，再依金額影響 60%＋超標程度 30%＋出清/報廢雙重異常 10% 排序。';else if(/出清率超標/.test(h.textContent))sub.textContent='異常偵測｜只看出清率超過警戒值的商品，依超標程度排序。';else if(/報廢率超標/.test(h.textContent))sub.textContent='異常偵測｜報廢率＝報廢金額 ÷ 營業額，依超標程度排序。';else if(/損耗率超標/.test(h.textContent))sub.textContent='異常偵測｜損耗率＝（出清＋報廢）÷ 營業額，依超標程度排序。'})}
 function top10(){document.querySelectorAll('#anomaly *').forEach(el=>{if(el.childNodes.length===1&&el.firstChild.nodeType===3&&/Top 20/.test(el.textContent))el.textContent=el.textContent.replace(/Top 20/g,'Top 10')});const root=document.querySelector('#anomaly .anomaly-rank-v519');if(root)root.querySelectorAll('.ar519-panel:not(.ar519-priority):not(.v6-clearance-amount) .ar519-row').forEach((el,i)=>{});}
 function orderInsight(){const page=document.getElementById('overview');if(!page)return;const structure=page.querySelector('.v522-insight-structure');if(!structure)return;const result=[...page.querySelectorAll('section,.panel,.exec-v513')].find(e=>/本期營運結果|PERIOD RESULT/.test(e.textContent||''));if(result&&result.nextElementSibling!==structure)result.after(structure)}
 function run(){clearanceTop10();anomalyLabels();top10();orderInsight()}
 run();setInterval(run,600);
})();
</script>'''
s=s.replace('Top 20','Top 10').replace('.slice(0,20)','.slice(0,10)')
s=s.replace('</head>',css+'\n</head>',1)
s=s.replace('</body>',js+'\n</body>',1) if '</body>' in s else s+js
p.write_text(s,encoding='utf-8')
print('OpsPilot v6 product rebuild applied')
