from pathlib import Path
import re
p=Path('index.html'); s=p.read_text(encoding='utf-8')
for tag in ['anomaly-top20-v516-css','anomaly-top20-v516-js']:
 s=re.sub(rf'<style id="{tag}">.*?</style>','',s,flags=re.S)
 s=re.sub(rf'<script id="{tag}">.*?</script>','',s,flags=re.S)
css='''<style id="anomaly-top20-v516-css">
#anomaly .anomaly-v58{display:none!important}
#anomaly .anomaly-top20-v516{display:grid;gap:12px;margin-bottom:14px}
.at20-head{padding:17px;border-radius:20px;background:linear-gradient(145deg,#0b1425,#17345d);color:#fff}.at20-top{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.at20-kicker{font-size:9px;font-weight:900;letter-spacing:.16em;color:#9db8e8}.at20-head h2{margin:5px 0 4px;font-size:21px}.at20-head p{margin:0;color:#bfd0e5;font-size:10px;line-height:1.5}.at20-settings{border:1px solid rgba(255,255,255,.18);background:rgba(255,255,255,.09);color:#fff;border-radius:12px;padding:9px 11px;font-size:10px;font-weight:900;white-space:nowrap}.at20-chips{display:flex;gap:7px;flex-wrap:wrap;margin-top:12px}.at20-chip{padding:6px 8px;border-radius:999px;background:rgba(255,255,255,.09);border:1px solid rgba(255,255,255,.12);font-size:9px;font-weight:800;color:#dbe7f5}
.at20-summary{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.at20-stat{padding:12px;border:1px solid var(--line);border-radius:14px;background:#fff}.at20-stat span{display:block;color:var(--muted);font-size:8px;font-weight:850}.at20-stat b{display:block;margin-top:4px;font-size:20px}.at20-list{display:grid;gap:9px}.at20-card{padding:13px 14px;border:1px solid var(--line);border-radius:17px;background:#fff;box-shadow:0 6px 18px rgba(23,43,77,.045)}.at20-card.high{border-left:4px solid #df4848}.at20-card.mid{border-left:4px solid #e7a036}.at20-card.low{border-left:4px solid #7990b4}.at20-title{display:grid;grid-template-columns:30px minmax(0,1fr) auto;gap:9px;align-items:center}.at20-rank{width:30px;height:30px;border-radius:10px;background:#f1f4f8;display:grid;place-items:center;font-size:10px;font-weight:950}.at20-name{min-width:0}.at20-name b{display:block;font-size:13px;line-height:1.35}.at20-name small{display:block;margin-top:3px;color:#8a94a4;font-size:8px}.at20-reason{padding:5px 7px;border-radius:999px;font-size:8px;font-weight:950;background:#f3f5f8;color:#536174;white-space:nowrap}.at20-card.high .at20-reason{background:#feecec;color:#c83434}.at20-card.mid .at20-reason{background:#fff3d9;color:#9a5a00}.at20-metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin-top:11px}.at20-metric{padding:9px 10px;border-radius:12px;background:#f8fafc;border:1px solid #e8edf3}.at20-metric span{display:block;color:#7f8999;font-size:8px;font-weight:800}.at20-metric b{display:block;margin-top:4px;font-size:12px}.at20-rates{display:flex;gap:10px;flex-wrap:wrap;margin-top:9px;padding-top:9px;border-top:1px dashed #dfe5ec;color:#68778a;font-size:9px}.at20-rates b{color:#26374d}.at20-empty{padding:18px;text-align:center;border:1px dashed #d8dee8;border-radius:14px;color:var(--muted);font-size:10px;background:#fafbfc}
@media(max-width:620px){.at20-metrics{grid-template-columns:1fr 1fr 1fr}.at20-metric{padding:8px}.at20-metric b{font-size:11px}.at20-title{grid-template-columns:28px minmax(0,1fr) auto}.at20-rank{width:28px;height:28px}.at20-name b{font-size:12px}.at20-reason{font-size:7.5px}}
</style>'''
js='''<script id="anomaly-top20-v516-js">
(function(){
 const KEY='opsAnomalyThresholdsV58', money=v=>v==null||!Number.isFinite(Number(v))?'—':new Intl.NumberFormat('zh-TW',{style:'currency',currency:'TWD',maximumFractionDigits:0}).format(Number(v)), pct=v=>v==null||!Number.isFinite(Number(v))?'—':(Number(v)*100).toFixed(2)+'%', n=v=>Number.isFinite(Number(v))?Number(v):0, esc=v=>String(v??'—').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 function getT(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');return x&&Number.isFinite(x.clearance)&&Number.isFinite(x.waste)?x:null}catch{return null}}
 function items(){const m=new Map();(window.rows||[]).forEach(r=>{const k=String(r.sku||r.item||'').trim();if(!k)return;if(!m.has(k))m.set(k,{name:r.item||r.sku,sales:0,clearance:0,waste:0});const x=m.get(k);x.sales+=n(r.sales);x.clearance+=n(r.clearance??r.clearanceAmount);x.waste+=n(r.waste??r.wasteAmount)});return [...m.values()].map(x=>({...x,loss:x.clearance+x.waste,cr:x.sales>0?x.clearance/x.sales:null,wr:x.sales>0?x.waste/x.sales:null,lr:x.sales>0?(x.clearance+x.waste)/x.sales:null}))}
 function reason(x,t,a){const ct=t?.clearance||0,wt=t?.waste||0,dual=ct&&wt&&x.cr!=null&&x.wr!=null&&x.cr>ct&&x.wr>wt,losses=a.map(v=>v.loss).filter(v=>v>0).sort((q,w)=>w-q),cut=losses[Math.min(losses.length-1,Math.max(0,Math.ceil(losses.length*.2)-1))]||Infinity,highAmount=x.loss>=cut,extreme=x.lr!=null&&x.lr>=1,highRate=x.lr!=null&&x.lr>=.3;if(dual)return '雙重超標';if(highAmount&&highRate)return '金額高＋損耗率高';if(extreme)return '損耗率極高';if(highAmount)return '損耗金額高';if(ct&&x.cr>ct)return '出清率超標';if(wt&&x.wr>wt)return '報廢率超標';return '需關注'}
 function score(x,t,maxLoss){const ct=t?.clearance||0,wt=t?.waste||0,impact=x.loss/maxLoss,ce=ct&&x.cr!=null?Math.max(0,x.cr/ct-1):0,we=wt&&x.wr!=null?Math.max(0,x.wr/wt-1):0,over=Math.min(1,Math.max(ce,we)/2),dual=ct&&wt&&x.cr>ct&&x.wr>wt?1:0;return impact*.5+over*.3+dual*.2}
 function severity(x,t){const dual=t&&x.cr>t.clearance&&x.wr>t.waste, extreme=x.lr!=null&&x.lr>=1;if(dual||extreme)return 'high';if((t&&((x.cr||0)>t.clearance||(x.wr||0)>t.waste))||(x.lr||0)>=.3)return 'mid';return 'low'}
 function ensure(){const page=document.getElementById('anomaly');if(!page)return null;let root=page.querySelector('.anomaly-top20-v516');if(!root){root=document.createElement('div');root.className='anomaly-top20-v516';const old=page.querySelector('.anomaly-v58,.anomaly-center-panel');old?old.before(root):page.prepend(root)}return root}
 function render(){const root=ensure();if(!root)return;const t=getT(),a=items();root.innerHTML=`<section class="at20-head"><div class="at20-top"><div><div class="at20-kicker">ANOMALY PRIORITY</div><h2>異常商品 Top 20</h2><p>依損耗金額、超標程度與雙重異常排序；畫面只呈現數據與排序原因，不提供建議動作。</p></div><button type="button" class="at20-settings">⚙︎ 判定設定</button></div>${t?`<div class="at20-chips"><span class="at20-chip">出清率警戒 ${pct(t.clearance)}</span><span class="at20-chip">報廢率警戒 ${pct(t.waste)}</span></div>`:''}</section><div class="at20-body"></div>`;const body=root.querySelector('.at20-body');if(!t){body.innerHTML='<div class="at20-empty">請先設定出清率與報廢率警戒值。</div>';return}if(!window.confirmed||!a.length){body.innerHTML='<div class="at20-empty">匯入並確認資料後產生 Top 20。</div>';return}const maxLoss=Math.max(...a.map(x=>x.loss),1);a.forEach(x=>x.ps=score(x,t,maxLoss));const ranked=a.filter(x=>x.loss>0||x.cr>t.clearance||x.wr>t.waste).sort((x,y)=>y.ps-x.ps||y.loss-x.loss).slice(0,20);const over=ranked.filter(x=>(x.cr||0)>t.clearance||(x.wr||0)>t.waste).length,dual=ranked.filter(x=>(x.cr||0)>t.clearance&&(x.wr||0)>t.waste).length;body.innerHTML=`<div class="at20-summary"><div class="at20-stat"><span>Top 20</span><b>${ranked.length}</b></div><div class="at20-stat"><span>超標商品</span><b>${over}</b></div><div class="at20-stat"><span>雙重超標</span><b>${dual}</b></div></div><div class="at20-list" style="margin-top:10px">${ranked.map((x,i)=>`<article class="at20-card ${severity(x,t)}"><div class="at20-title"><div class="at20-rank">${i+1}</div><div class="at20-name"><b>${esc(x.name)}</b><small>損耗 ${money(x.loss)}・損耗率 ${pct(x.lr)}</small></div><span class="at20-reason">${reason(x,t,a)}</span></div><div class="at20-metrics"><div class="at20-metric"><span>營業額</span><b>${money(x.sales)}</b></div><div class="at20-metric"><span>出清金額</span><b>${money(x.clearance)}</b></div><div class="at20-metric"><span>報廢金額</span><b>${money(x.waste)}</b></div></div><div class="at20-rates"><span>出清率 <b>${pct(x.cr)}</b></span><span>報廢率 <b>${pct(x.wr)}</b></span><span>損耗率 <b>${pct(x.lr)}</b></span></div></article>`).join('')}</div>`}
 document.addEventListener('click',e=>{if(e.target.closest('.at20-settings'))document.querySelector('.av58-settings')?.click()});const old=window.renderAll;if(typeof old==='function')window.renderAll=function(){const r=old.apply(this,arguments);setTimeout(render,0);return r};document.addEventListener('DOMContentLoaded',render);setTimeout(render,0);window.renderAnomalyTop20V516=render;
})();
</script>'''
s=s.replace('</head>',css+'</head>',1);s=s.replace('</body>',js+'</body>',1);p.write_text(s,encoding='utf-8');print('anomaly top20 v5.16 patched')
