from pathlib import Path
import re
p=Path('index.html'); s=p.read_text(encoding='utf-8')
for tag in ['executive-summary-v513-css','executive-summary-v513-js']:
 s=re.sub(rf'<style id="{tag}">.*?</style>','',s,flags=re.S); s=re.sub(rf'<script id="{tag}">.*?</script>','',s,flags=re.S)
css='''<style id="executive-summary-v513-css">
#executive .hero,#executive .trust-strip,#executive>.grid-2{display:none!important}#executive .exec-v513{display:grid;gap:12px}.ex513-period{padding:10px 12px;border:1px solid var(--line);border-radius:13px;background:#fff;color:#667085;font-size:10px;font-weight:750}.ex513-summary{padding:16px 17px;border-radius:19px;background:linear-gradient(145deg,#0b1425,#17345d);color:#fff}.ex513-summary small{display:block;color:#9db8e8;font-size:9px;font-weight:900;letter-spacing:.14em}.ex513-summary strong{display:block;margin-top:7px;font-size:17px;line-height:1.45}.ex513-kpis{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.ex513-kpi{padding:13px;border:1px solid var(--line);border-radius:16px;background:#fff}.ex513-kpi span{display:block;color:#7b879b;font-size:9px;font-weight:800}.ex513-kpi b{display:block;margin-top:5px;font-size:19px;letter-spacing:-.035em}.ex513-ranks{display:grid;grid-template-columns:1fr 1fr;gap:10px}.ex513-card{padding:15px;border:1px solid var(--line);border-radius:19px;background:#fff;box-shadow:0 8px 24px rgba(22,36,66,.04)}.ex513-head{display:flex;justify-content:space-between;align-items:end;margin-bottom:7px}.ex513-head h3{margin:0;font-size:15px}.ex513-head span{font-size:8px;font-weight:900;color:#738096}.ex513-row{display:grid;grid-template-columns:25px minmax(0,1fr) auto;gap:8px;align-items:center;padding:9px 0;border-bottom:1px solid #edf0f4}.ex513-row:last-child{border-bottom:0}.ex513-no{width:25px;height:25px;border-radius:8px;background:#f1f4f8;display:grid;place-items:center;font-size:9px;font-weight:950}.ex513-name{min-width:0}.ex513-name b{display:block;font-size:11px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.ex513-name small{display:block;margin-top:2px;color:#8a94a4;font-size:8px}.ex513-val{text-align:right;font-size:11px;font-weight:900}.ex513-val small{display:block;font-size:8px;color:#8a94a4;margin-top:2px}.ex513-events{margin-top:0}#overview .page-head h1{font-size:0}#overview .page-head h1:after{content:'洞察';font-size:32px}#overview .page-head .eyebrow{font-size:0}#overview .page-head .eyebrow:after{content:'OPERATIONS INSIGHT';font-size:11px}#overview .page-head p{font-size:0}#overview .page-head p:after{content:'看趨勢、結構與數字背後的變化。';font-size:13px}
@media(max-width:760px){.ex513-kpis{grid-template-columns:1fr 1fr}.ex513-ranks{grid-template-columns:1fr}.ex513-kpi{padding:12px}.ex513-kpi b{font-size:18px}.ex513-summary strong{font-size:16px}}
</style>'''
js='''<script id="executive-summary-v513-js">
(function(){
 const money=v=>v==null||!Number.isFinite(Number(v))?'—':new Intl.NumberFormat('zh-TW',{style:'currency',currency:'TWD',maximumFractionDigits:0}).format(Number(v));
 const pct=v=>v==null||!Number.isFinite(Number(v))?'—':(Number(v)*100).toFixed(2)+'%'; const n=v=>Number.isFinite(Number(v))?Number(v):0; const esc=v=>String(v??'—').replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]));
 function agg(){const m=new Map();(window.rows||[]).forEach(r=>{const k=String(r.sku||r.item||'').trim();if(!k)return;if(!m.has(k))m.set(k,{name:r.item||r.sku,sales:0,clearance:0,waste:0});const x=m.get(k);x.sales+=n(r.sales);x.clearance+=n(r.clearance??r.clearanceAmount);x.waste+=n(r.waste??r.wasteAmount)});return [...m.values()].map(x=>({...x,loss:x.clearance+x.waste,cr:x.sales>0?x.clearance/x.sales:null,wr:x.sales>0?x.waste/x.sales:null,lr:x.sales>0?(x.clearance+x.waste)/x.sales:null}))}
 function thresholds(){try{return JSON.parse(localStorage.getItem('opsAnomalyThresholdsV58')||'null')}catch{return null}}
 function priority(a){if(!a.length)return[];const t=thresholds(),ct=t?n(t.clearance):0,wt=t?n(t.waste):0,max=Math.max(...a.map(x=>x.loss),1);a.forEach(x=>{const impact=x.loss/max,ce=ct&&x.cr!=null?Math.max(0,x.cr/ct-1):0,we=wt&&x.wr!=null?Math.max(0,x.wr/wt-1):0,over=Math.min(1,Math.max(ce,we)/2),dual=ct&&wt&&x.cr>ct&&x.wr>wt?1:0;x.ps=impact*.5+over*.3+dual*.2});return [...a].sort((x,y)=>y.ps-x.ps||y.loss-x.loss).slice(0,5)}
 function rank(title,key,fmt,meta){const a=agg().filter(x=>x[key]!=null&&n(x[key])!==0).sort((x,y)=>n(y[key])-n(x[key])).slice(0,5);return card(title,a.map((x,i)=>row(i,x.name,fmt(x[key]),meta(x))))}
 function row(i,name,val,sub){return `<div class="ex513-row"><i class="ex513-no">${i+1}</i><div class="ex513-name"><b>${esc(name)}</b><small>${sub||''}</small></div><div class="ex513-val">${val}</div></div>`}
 function card(title,body){return `<section class="ex513-card"><div class="ex513-head"><h3>${title}</h3><span>TOP 5</span></div>${body.length?body.join(''):'<div class="empty">無資料</div>'}</section>`}
 function period(rr){const ps=rr.map(r=>r.periodStart).filter(Boolean).sort(),pe=rr.map(r=>r.periodEnd).filter(Boolean).sort();if(ps.length&&pe.length)return `${ps[0]} ～ ${pe[pe.length-1]}`;const ds=rr.map(r=>r.date instanceof Date&&!isNaN(r.date)?r.date:null).filter(Boolean).sort((a,b)=>a-b);return ds.length?`${ds[0].toLocaleDateString('zh-TW')} ～ ${ds[ds.length-1].toLocaleDateString('zh-TW')}`:'資料期間未提供'}
 function render(){const page=document.getElementById('executive');if(!page)return;let root=page.querySelector('.exec-v513');if(!root){root=document.createElement('div');root.className='exec-v513';page.querySelector('.page-head')?.after(root)}const rr=Array.isArray(window.rows)?window.rows:[],a=agg(),sales=a.reduce((s,x)=>s+x.sales,0),clear=a.reduce((s,x)=>s+x.clearance,0),waste=a.reduce((s,x)=>s+x.waste,0),loss=clear+waste,lr=sales>0?loss/sales:null,cr=sales>0?clear/sales:null,wr=sales>0?waste/sales:null,top=[...a].sort((x,y)=>y.loss-x.loss)[0];const p=priority(a);root.innerHTML=`<div class="ex513-period">${period(rr)}｜已匯入資料即時計算</div><div class="ex513-summary"><small>本期摘要</small><strong>${rr.length?`營業額 ${money(sales)}，總損耗率 ${pct(lr)}${top&&top.loss>0?`，目前損耗金額最高為「${esc(top.name)}」。`: '。'}`:'匯入並確認資料後，這裡會產生本期摘要。'}</strong></div><div class="ex513-kpis"><div class="ex513-kpi"><span>營業額</span><b>${money(sales)}</b></div><div class="ex513-kpi"><span>總損耗率</span><b>${pct(lr)}</b></div><div class="ex513-kpi"><span>總出清率</span><b>${pct(cr)}</b></div><div class="ex513-kpi"><span>總報廢率</span><b>${pct(wr)}</b></div><div class="ex513-kpi"><span>總出清金額</span><b>${money(clear)}</b></div><div class="ex513-kpi"><span>總報廢金額</span><b>${money(waste)}</b></div></div><div class="ex513-ranks">${rank('銷售商品','sales',money,x=>`營業額占比 ${sales>0?pct(x.sales/sales):'—'}`)}${rank('出清商品','clearance',money,x=>`出清率 ${pct(x.cr)}`)}${rank('報廢商品','waste',money,x=>`報廢率 ${pct(x.wr)}`)}${card('需改善商品',p.map((x,i)=>row(i,x.name,Math.round(x.ps*100)+' 分',`損耗 ${money(x.loss)}・損耗率 ${pct(x.lr)}`)))}</div>`;
 const ev=document.getElementById('externalEventPanel');if(ev&&ev.parentElement!==page){ev.classList.add('ex513-events');page.appendChild(ev)}
 }
 function rename(){const ex=document.querySelector('.nav-btn[data-page="executive"] span'),ov=document.querySelector('.nav-btn[data-page="overview"] span');if(ex)ex.textContent='總覽';if(ov)ov.textContent='洞察';const h=document.querySelector('#executive .page-head h1'),ey=document.querySelector('#executive .page-head .eyebrow'),pp=document.querySelector('#executive .page-head p');if(h)h.textContent='總覽';if(ey)ey.textContent='EXECUTIVE OVERVIEW';if(pp)pp.textContent='一頁掌握本期結果、商品排行與改善優先順序。'}
 const old=window.renderAll;if(typeof old==='function')window.renderAll=function(){const r=old.apply(this,arguments);setTimeout(()=>{rename();render()},0);return r};document.addEventListener('DOMContentLoaded',()=>{rename();render()});setTimeout(()=>{rename();render()},0);
})();
</script>'''
s=s.replace('</head>',css+'</head>',1);s=s.replace('</body>',js+'</body>',1);p.write_text(s,encoding='utf-8');print('executive summary v5.13 patched')
